# è®¾ç½®baseURLä¸”ä½¿ç”¨ç›¸å¯¹URL
baseURL = "http://example.org/"
relativeURLs = true



# [en, zh-cn, fr, ...] è®¾ç½®é»˜è®¤çš„è¯­è¨€
defaultContentLanguage = "zh-cn"
# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™
languageCode = "zh-CN"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true
# ç½‘ç«™æ ‡é¢˜
title = "Sunliag's blog"

# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme = "LoveIt"

[params]

  # LoveIt ä¸»é¢˜ç‰ˆæœ¬
  version = "0.2.X"
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    # é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
    [params.header.title]
      # URL of the LOGO
      # LOGO çš„ URL
      logo = "/avatar.png"
      # title name
      # æ ‡é¢˜åç§°
      name = "Sunliag's Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      post = ""
      # whether to use typeit animation for title name
      # æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = false
[params.home]
    # amount of RSS pages
    # RSS æ–‡ç« æ•°ç›®
    rss = 10
    # Home page profile
    # ä¸»é¡µä¸ªäººä¿¡æ¯
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail = ""
      # URL of avatar shown in home page
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "/favicon.png"
      # title shown in home page (HTML format is supported)
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜ (å…è®¸ HTML æ ¼å¼)
      subtitle = "è®°å½• åˆ†äº« å­¦ä¹  è¿›æ­¥"
      # whether to use typeit animation for subtitle
      # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = true
      # whether to show social links
      # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
      social = true
      # disclaimer (HTML format is supported)
      # å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
      disclaimer = ""
    # Home page posts
    # ä¸»é¡µæ–‡ç« åˆ—è¡¨
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      # ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
      paginate = 6
  # Social config in home page
  # ä¸»é¡µçš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
  [params.social]
    GitHub = "95270w0"
    Skype = "live:2820725552"
    Email = "sunyongliang233@gmail.com"
    
 # Footer config
  # é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
    custom = ""
    # whether to show Hugo and theme info
    # æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
    hugo = true
    # whether to show copyright info
    # æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
    copyright = true
    # whether to show the author
    # æ˜¯å¦æ˜¾ç¤ºä½œè€…
    author = true
    # site creation time
    # ç½‘ç«™åˆ›ç«‹å¹´ä»½
    since = 2022
    # ICP info only in China (HTML format is supported)
    # ICP å¤‡æ¡ˆä¿¡æ¯ï¼Œä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
    icp = "222222"
    # license info (HTML format is supported)
    # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
    license= ""

[menu]
  [[menu.main]]
    identifier = "posts"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    pre = ""
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    post = ""
    name = "ğŸ“–æ–‡ç« "
    url = "/posts/"
    # å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "ğŸ·æ ‡ç­¾"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "ğŸ—‚åˆ†ç±»"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  # è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false æ˜¯å¿…è¦çš„è®¾ç½® (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
